### ISSUE TITLE
AEP Web SDK 2.2.0 - checkout- Uncaught (in promise) TypeError: [alloy] Cannot convert object to primitive value  at String (<anonymous>)

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/alloy#611]
### Expected Behaviour
It is expected that this error does not happen (which prevent the xdm from being sent).

### Actual Behaviour
On my test implementation (https://www.seven-goats.com - Password : "goats") , when placing an order and being shown the order confirmation page, there is an "AEP Web SDK - Send Event" action.  In the console, there are a few errors:

![Screen Shot 2020-10-15 at 11 32 32 AM](https://user-images.githubusercontent.com/22940746/96159438-42203b00-0eda-11eb-882e-649bf9a18f4c.png)

Because of this error, the action does not actually send the xdm event. 
If I reload the page, everything works as expected. 

Other notes: I have "Disable cache" enabled on my Network Settings in Chrome. 

### Reproduce Scenario (including but not limited to)
0) Open Chrome Dev Tools, enable Launch Debug and Alloy debug, set log level to include verbose)
1) Navigate to [https://www.seven-goats.com ](url). Use the password "goats" for entry.
2) Add a goat or two to the shopping cart.
3) Proceed to Checkout. 
4) Use any valid address for shipping / billing.  On the payment page enter "1" as the credit card number. Enter "Bogus Gateway" as the Name on the Credit card.  Expiration 02/22,  CVV: 222
5) Place order and observe the errors in the console. 

#### Steps to Reproduce
See above. 

#### Platform and Version
Launch / AEP Web SDK 2.2.0

**Comment by jfkhoury** [comment]
Thank you @stewartschillingsdi . We will look into this and get back to you shortly.

Jira: https://jira.corp.adobe.com/browse/CORE-53571

**Comment by jonsnyder** [comment]
I was able to reproduce the error. You also need to be debugging for the error to occur. (i.e. `_satellite.setDebug(true)`). This is what is happening:

1. The console logger is overwritten by some code on the page (Maybe Shopify code?)
2. During the configure command, Alloy is logging the computed configuration object to the console. This object was created with "Object.create(null)".
3. The overwritten console logger calls `String(loggedObject)` which throws an error because the loggedObject does not have a "toString" object.

I am working on a fix to make sure the object will have a toString method. This will probably go out with the next Alloy/Alloy Extension release. In the mean time here are some workarounds:

Workarounds:
1. Turn off debugging (_satellite.setDebug(false))
2. You can leave Launch debugging on and turn off alloy debugging: `_satellite.setDebug(true); alloy("setDebug", {enabled: false});`
3. Remove the code on the page that overwrites console.info

**Comment by stewartschillingsdi** [comment]
@jonsnyder,  I am quite honored that you named your branch "sevengoats".

**Comment by jfkhoury** [comment]
This fix should be released on Oct 28th
