### ISSUE TITLE
CommonJS module imported in ES module

### ISSUE THREAD

**Issue by GeorgeTailor** [adobe/alloy#711]
### Expected Behaviour

`@adobe/reactor-object-assign` should export its resources with ES syntax instead of commonJS. Currently, it uses:
```
module.exports = require('object-assign');
```
instead of 
```
import assign from "object-assign';
export default assign;
```
or something like that

### Actual Behaviour

Error is thrown when trying to build the library:
```
Error: 'default' is not exported by node_modules/@adobe/reactor-object-assign/index.js, imported by node_modules/@adobe/alloy/libEs6/utils/assign.js
```

#### Steps to Reproduce

- `npm i @adobe/alloy`
- try to import it in code via `import {createInstance} from "@adobe/alloy";`
- build with rollup

The problem can be resolved by using https://github.com/rollup/plugins/tree/master/packages/commonjs but IMO it should not be required. The package should be fully exported as an ES module.

**Comment by jonsnyder** [comment]
Thanks for your feedback.

We use the @adobe/reactor-* packages because when we build the alloy Adobe Launch extension, those packages are already included. You are right though that those packages are using commonJS syntax: https://github.com/adobe/reactor-turbine/blob/master/coreModulePackages/objectAssign/index.js

I think we would need to remove these as dependencies to fix this issue. We will discuss this issue as a team.

**Comment by Aaronius** [comment]
Hi @GeorgeTailor, thanks for reporting this. This issue goes beyond the npm packages that Adobe owns. You may already understand this, but I'll try to illustrate just to make sure it's clear.

Even if we change `@adobe/reactor-object-assign` to be an ES6 module as you've outlined, the `object-assign` package, which `@adobe/reactor-object-assign` leverages, is still a CommonJS module. You would receive an error in this case, though the error message would complain about `object-assign` being a CommonJS module rather than `@adobe/reactor-object-assign`.

Alloy leverages several public npm packages that are CommonJS modules that are not maintained by Adobe: `js-cookie` (through @adobe/reactor-cookie), querystring (through @adobe/reactor-query-string), uuid (directly), and css.escape (directly). Some npm packages may depend on other packages that consist of CommonJS modules.

In other words, to satisfy what you're requesting, Alloy would need to avoid usage of any npm packages (or their dependencies) that consist of CommonJS modules. In an ideal world, the JavaScript ecosystem would have completely moved past CommonJS modules and onto ES6 modules, but we're not there yet. For the foreseeable future, Alloy will continue leveraging some npm packages consisting of CommonJS modules.

Some bundlers, like Webpack, automatically handle bundling CommonJS modules. Rollup has chosen to only support bundling CommonJS modules by using a plugin, as you've described. As you may have noticed, it won't even bundle ES6 packages from node_modules without a plugin. We've decided to add documentation giving people a heads up that we leverage npm packages consisting of CommonJS modules and that they may need to configure their bundler accordingly. We have a separate, internal ticket to track that work.

Thanks for reporting this and sorry it's not the resolution you were hoping for.
