### ISSUE TITLE
Feature Request: Send events while opted-out of ECID

### ISSUE THREAD

**Issue by and-poulsen** [adobe/alloy#756]
We have very strict cookie regulations in Europe, and in Denmark specifically. This means that we can't really set any cookies if the user opts out of the CMP.

It seems as though if you use the "Set Consent" with the Adobe 2.0 standard and pass a "n" (opt-out) value, that will then kill all "Send Event" actions:
>The sendEvent command could not fully complete. Caused by: The user declined consent.

We want to still track page views despite the user opting out - in this case we want to disable ECID and provide our own ID (either a first-party user ID if logged in, or otherwise an anonymous frequency capped ID)

In AppMeasurement there is a more granular consent option through "adobe.optIn" where you could enable Analytics, but disable ECID ( `{aa: true, ecid: false}`)

**Comment by maximilianoertel** [comment]
We're running into the exact same issue on one of our projects, now forcing us to fully disable Analytics even if the user only opt-out of the category under which ECID falls. Given that this issue is just under a year old, I was wondering if Adobe had any plans of introducing granular consent into the Web SDK?

**Comment by jfkhoury** [comment]
Hey @maximilianoertel , We are planning on introducing granular consent, but it won'd include supporting events without an ECID.
